
export const SHOW_FEEDBACK_FORM = "SHOW_FEEDBACK_FORM";
export const HIDE_FEEDBACK_FORM = "HIDE_FEEDBACK_FORM";

export const SET_ACTIVE_SECTION_INDEX = "SET_ACTIVE_SECTION_INDEX";

export const SET_CALC_TANTAMARESKI_RESULT = "SET_CALC_TANTAMARESKI_RESULT";

